# data_path: /data1/wh/ImageNet1K/train
# val_data_path: /data1/wh/ImageNet1K/val
data_path: /nfs_beijing/kubeflow-user/wanghao/workspace/ai4sci/imagenet/train
val_data_path: /nfs_beijing/kubeflow-user/wanghao/workspace/ai4sci/imagenet/val
save_best: true
image_size: 256
vq_model: VQ-16
enc_type: dinov2
dec_type: dinov2
semantic_guide: dinov2
batch_size: 64
epochs: 50
lr_scheduler: constant
lr: 1e-4
disc_lr: 1e-4
#max_grad_norm: 1.0
#reconstruction_weight: 4.0
codebook_embed_dim: 64
codebook_size: 4096
abs_pos_embed: true
product_quant: 1
ema: true
codebook_drop: 0.0
encoder_model: vit_base_patch14_dinov2.lvd142m
decoder_model: vit_base_patch14_dinov2.lvd142m
num_latent_tokens: 256
v_patch_nums: [16]
half_sem: false
guide_type_1: class
start_drop: 3
ckpt_every: 10000
sem_loss_weight: 0.1
enc_tuning_method: full
lecam_loss_weight: 0.001
weight_decay: 0.0
disc_weight_decay: 0.0005
disc_epoch_start: 2
disc_type: dinodisc
aug_fade_steps: 0
disc_adaptive_weight: true
cloud_save_path: XQGAN-4096
vq_type: 'rotfsq'
results_dir: results_rotfsq_4096
ex_name: VQ-4096-rotfsq
dataset: imagenet